### ISSUE TITLE
Next and Previous Buttons not Working on Windows 10

### ISSUE THREAD

**Issue by pufflegamerz** [heb12/heb12-desktop#43]
**Describe the bug**
The next and previous arrow keys don't do anything when clicked

**To Reproduce**
1. Open App
2. Click on arrow

**Expected behavior**
The chapter should increase by 1.

**Desktop (please complete the following information):**
 - Windows 10 Pro Version 10.0.17134 Build 17134
- Heb12 Desktop v0.3.0

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz This is a bug that was in that specific compilation of the code. The v0.3.0 code branch should not contain that bug as it was fixed in "Fix arrow buttons" in https://github.com/heb12/heb12-desktop/commits/v0.3.0. I am sorry, maybe you can [make a new binary](https://github.com/heb12/heb12-desktop/wiki/Packaging) for Windows with the latest 0.3.0 code? I plan to release 0.4.0 soon anyway, but I don't have much time to do anything at the moment.

**Comment by pufflegamerz** [comment]
Ok.
